Website = "https://github.com/Zokiio/hytale-voicechat"

[Details]
Icon = "Icon.png"
Name = "Hytale Voice Chat"
ID = "com.zottik.hytale-voicechat"
Version = "1.0.0"
Build = 9

[LinuxAndBSD]
GenericName = "Voice Chat Client"
Categories = ["Network", "Audio"]
Comment = "Proximity voice chat client for Hytale"
Keywords = ["hytale", "voice", "chat", "audio"]
