Website = "https://hytale.com"
Icon = "internal/client/resources/Icon.png"

[Details]
  Name = "Hytale Voice Chat"
  ID = "com.zottik.hytale-voicechat"
  Version = "1.0.0"
  Build = 1

[Windows]
  CompanyName = "Zottik"
  FileDescription = "Voice Chat Client for Hytale"
  InternalName = "HytaleVoiceChat"
  LegalCopyright = "Copyright Â© 2026 Zottik"
  OriginalFilename = "HytaleVoiceChat.exe"
  ProductName = "Hytale Voice Chat"


